First Question ===>>   it's purpose of this challenge is to get you thinking the mechancs of matrix multiplication

In [6]:
import numpy as np
import matplotlib.pyplot as pl
A=np.random.randn(4,2)
B=np.random.randn(4,2)
C=np.zeros((2,2))
for coli in range(2):
    for colj in range (2):
     C[coli,colj]=np.dot(A[: ,coli],B[:, colj])
print(C)
        

[[-3.34180325  2.36301466]
 [ 2.22047442 -3.19524785]]


Second Question -->>  We  can Just discoverd one way to make a symmetric matrix 

In [11]:
import numpy as np
import matplotlib.pyplot as plt
V=np.random.randn(4,4)
VT=np.tril(V)
print("Original matrix   \n",(VT))
S=VT+VT.T
# we can round off the matrix
RS=np.round(100*S)
print("\n Restul is  >  \n" ,(RS))

Original matrix   
 [[-1.68108345  0.          0.          0.        ]
 [-0.04264765 -1.08788014  0.          0.        ]
 [ 1.28835899 -0.29296449  1.36273844  0.        ]
 [ 0.29796255 -0.13850684  0.35662287 -0.20442444]]

 Restul is  >  
 [[-336.   -4.  129.   30.]
 [  -4. -218.  -29.  -14.]
 [ 129.  -29.  273.   36.]
 [  30.  -14.   36.  -41.]]


Third Question -->  The point here is to appreciate that indexing the diagonal of a matrix involves the i,j,indeces.


In [16]:
import numpy as np
D=np.zeros((4,8))
for d in range(min(D.shape)):
    D[d,d]=d+1
print("Result is  \n",(D))

Result is  
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0.]]
